#!/usr/bin/env groovy
pipeline {
    agent {
        docker { image 'node:14-alpine' }
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm run test'
            }
            post {
                failure {
                    mail to: 'team@example.com',
                    subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                }
            }
        }
    }
            
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
            post {
                failure {
                    mail to: 'team@example.com',
                    subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                }
            }
        }
    }
}